### PR TITLE
Add Windows Server 2016 Technical Preview 4 images

### PR DESCRIPTION
**Pull request by csandfeld**
Don't know if you are interested in supporting tech previews in the module. But if you are, this adds the Windows Server 2016 Technical Preview images to the media config

### CODE REVIEW

**Comment by iainbrighton** [comment]
I still have got around to testing these just yet. Would you mind trying one with the latest `Register-LabMedia` cmdlet in v0.8.5 - if you have time? They seem like a good candidate!

**Comment by csandfeld** [comment]
Sure thing. Will try it out shortly

**Comment by csandfeld** [comment]
Took a little longer than expected to find the time to test it, but finally managed.
I have tested with addition of a single image from the Win2016 TP4 media so far, and it seem to work a treat.

Ran the following:
```PowerShell
C:\> $Parameters = @{

    Id           = '2016TP4_x64_Standard_EN'
    MediaType    = 'ISO'
    Uri          = 'http://download.microsoft.com/download/C/2/5/C257AD1A-45C1-48F9-B31C-5D37D6463123/10586.0.151029-1700.TH2_RELEASE_SERVER_OEMRET_X64FRE_EN-US.ISO'
    Architecture = 'x64'

    Description  = 'Windows Server 2016 Technical Preview 4 Standard 64bit English'
    ImageName    = 'Windows Server 2016 Technical Preview 4 SERVERSTANDARD'
    Filename     = '2016TP4_x64_EN.iso'
    Checksum     = '935BA77651210BD1BD71A114C92B0CAA'

    CustomData   = @{ WindowsOptionalFeature = @('NetFx3') }
}


C:\> Register-LabMedia @Parameters -Verbose
```

Resulting in this output:
```PowerShell
C:\> Register-LabMedia @Parameters -Verbose
WARNING: [16:30:42] No custom media '2016TP4_x64_Standard_EN' registered.
VERBOSE: [16:30:42] Adding '2016TP4_x64_Standard_EN' media entry.
VERBOSE: [16:30:42] Saving configuration '2016TP4_x64_Standard_EN'.
VERBOSE: [16:30:42] Directory 'C:\ProgramData\VirtualEngineLab\Config' already exists.


Id           : 2016TP4_x64_Standard_EN
Filename     : 2016TP4_x64_EN.iso
Description  : Windows Server 2016 Technical Preview 4 Standard 64bit English
Architecture : x64
ImageName    : Windows Server 2016 Technical Preview 4 SERVERSTANDARD
MediaType    : ISO
Uri          : http://download.microsoft.com/download/C/2/5/C257AD1A-45C1-48F9-B31C-5D37D6463123/10586.0.151029-1700.TH2_RELEASE_SERVER_OEMRET_X64FRE_EN-US.ISO
Checksum     : 935BA77651210BD1BD71A114C92B0CAA
CustomData   : {WindowsOptionalFeature}
Hotfixes     : 
```

And this in the CustomMedia.json
```JSON
[
    {
        "Id":  "2016TP4_x64_Standard_EN",
        "Filename":  "2016TP4_x64_EN.iso",
        "Description":  "Windows Server 2016 Technical Preview 4 Standard 64bit English",
        "Architecture":  "x64",
        "ImageName":  "Windows Server 2016 Technical Preview 4 SERVERSTANDARD",
        "MediaType":  "ISO",
        "Uri":  "http://download.microsoft.com/download/C/2/5/C257AD1A-45C1-48F9-B31C-5D37D6463123/10586.0.151029-1700.TH2_RELEASE_SERVER_OEMRET_X64FRE_EN-US.ISO",
        "Checksum":  "935BA77651210BD1BD71A114C92B0CAA",
        "CustomData":  {
                           "WindowsOptionalFeature":  "NetFx3"
                       },
        "Hotfixes":  null
    }
]
```

I have also verified that I could deploy a VM with the new media, including download of media, and generation of parent VHDX.

**Comment by iainbrighton** [comment]
W00t! Thanks for testing.

Now – do we think the preview media should be in the included media list? Is having pre-release media a good idea?

My inclination would be ‘yes’ – where would you test pre-release software? In a lab of course!

**Comment by kilasuit** [comment]
I agree Iain - being in the labs included media list just makes sense :-)

**Comment by csandfeld** [comment]
For me it is a definite yes :+1:

**Comment by iainbrighton** [comment]
Thx!

**Comment by csandfeld** [comment]
Well ... thank you! :)

**Comment by iainbrighton** [comment]
From: Pluralsight [mailto:admin@pluralsight.com]
Sent: 18 December 2015 11:40
To: Iain Brighton <iain.brighton@virtualengine.co.uk>
Subject: Thanks for renewing with Pluralsight













[PLURALSIGHT]<http://tmail.pluralsight.com/track/click/30210868/www.pluralsight.com?p=eyJzIjoiNGNVRTUzbjIwS095MjRWaVlkRUJjUEZmZmZjIiwidiI6MSwicCI6IntcInVcIjozMDIxMDg2OCxcInZcIjoxLFwidXJsXCI6XCJodHRwOlxcXC9cXFwvd3d3LnBsdXJhbHNpZ2h0LmNvbVxcXC9cIixcImlkXCI6XCI4MTkzN2MwN2YwM2E0NzJiYWQ3ZmYxNmQ4YTMyNGJhY1wiLFwidXJsX2lkc1wiOltcImY2MjZiYjNkN2RkZGM1NTAxNWJhN2MwMzdkYTQwZWY5MzI4YTExZjJcIl19In0>



You’ve got Pluralsight for another month



Hi Iain,



Thanks for renewing your Pluralsight subscription! You can check the status of your subscription at any time by logging into your account. Keep learning with 4,500+ courses at your fingertips.



Log in<http://tmail.pluralsight.com/track/click/30210868/app.pluralsight.com?p=eyJzIjoiYTM1MnUxLThLYldaSS1SaWRUOWJzbFVOZnRjIiwidiI6MSwicCI6IntcInVcIjozMDIxMDg2OCxcInZcIjoxLFwidXJsXCI6XCJodHRwczpcXFwvXFxcL2FwcC5wbHVyYWxzaWdodC5jb21cXFwvXCIsXCJpZFwiOlwiODE5MzdjMDdmMDNhNDcyYmFkN2ZmMTZkOGEzMjRiYWNcIixcInVybF9pZHNcIjpbXCJkMWEzODNlYjA5MGZjNTNjNDFmZjViY2EyMjBmMGYwMTViYTcwMGZjXCJdfSJ9>















Happy learning!














[PLURALSIGHT]<http://tmail.pluralsight.com/track/click/30210868/www.pluralsight.com?p=eyJzIjoiNGNVRTUzbjIwS095MjRWaVlkRUJjUEZmZmZjIiwidiI6MSwicCI6IntcInVcIjozMDIxMDg2OCxcInZcIjoxLFwidXJsXCI6XCJodHRwOlxcXC9cXFwvd3d3LnBsdXJhbHNpZ2h0LmNvbVxcXC9cIixcImlkXCI6XCI4MTkzN2MwN2YwM2E0NzJiYWQ3ZmYxNmQ4YTMyNGJhY1wiLFwidXJsX2lkc1wiOltcImY2MjZiYjNkN2RkZGM1NTAxNWJhN2MwMzdkYTQwZWY5MzI4YTExZjJcIl19In0>



182 N Union Ave Suite 200 Farmington, UT 84025



[facebook]<http://tmail.pluralsight.com/track/click/30210868/www.facebook.com?p=eyJzIjoiMXFpUHdYRVh6ME00WUdFR2dfaU5ybU9oU2drIiwidiI6MSwicCI6IntcInVcIjozMDIxMDg2OCxcInZcIjoxLFwidXJsXCI6XCJodHRwOlxcXC9cXFwvd3d3LmZhY2Vib29rLmNvbVxcXC9wbHVyYWxzaWdodFwiLFwiaWRcIjpcIjgxOTM3YzA3ZjAzYTQ3MmJhZDdmZjE2ZDhhMzI0YmFjXCIsXCJ1cmxfaWRzXCI6W1wiMTM3YWIxZjgxMmM0YTk3YTI4NTk5NDI0MTQyZWRkOTAzNzU3OGI2N1wiXX0ifQ>



[instagram]



[twitter]<http://tmail.pluralsight.com/track/click/30210868/twitter.com?p=eyJzIjoiM0tLb3FvMzkxOEtBQ1FEbUVTYTBZWHVWMzFnIiwidiI6MSwicCI6IntcInVcIjozMDIxMDg2OCxcInZcIjoxLFwidXJsXCI6XCJodHRwOlxcXC9cXFwvdHdpdHRlci5jb21cXFwvcGx1cmFsc2lnaHRcIixcImlkXCI6XCI4MTkzN2MwN2YwM2E0NzJiYWQ3ZmYxNmQ4YTMyNGJhY1wiLFwidXJsX2lkc1wiOltcImFmNTZmNjZjZmMwMjBhMDYyZmJhYjBlYTc1ZGNlMWFkYzdjMGFhODJcIl19In0>



[linkedin]



[Google Plus]<http://tmail.pluralsight.com/track/click/30210868/plus.google.com?p=eyJzIjoiYUdYcmxRZVRrdldGRW0wVkJ1M0k4TnZIdXEwIiwidiI6MSwicCI6IntcInVcIjozMDIxMDg2OCxcInZcIjoxLFwidXJsXCI6XCJodHRwOlxcXC9cXFwvcGx1cy5nb29nbGUuY29tXFxcLytwbHVyYWxzaWdodFwiLFwiaWRcIjpcIjgxOTM3YzA3ZjAzYTQ3MmJhZDdmZjE2ZDhhMzI0YmFjXCIsXCJ1cmxfaWRzXCI6W1wiOGM4MzFiYzRkYzYxYTAwNzVjY2FmYTBmYjkyNTY5NGIzNTU0ZDgzNlwiXX0ifQ>



[You Tube]





Copyright© 2015 Pluralsight LLC.
All logos and trademarks are the properties of their respective owners.

**Comment by csandfeld** [comment]
@iainbrighton Did you intend to send your Pluralsight renewal mail this way?

**Comment by iainbrighton** [comment]
Errr no! How did that happen?! Thx - deleted!

**Comment by csandfeld** [comment]
Didn't think so

**Pull request merged**
